### ISSUE TITLE
Task failed!

### ISSUE THREAD

**Issue by morning-tan** [websoft9dev/role_postgresql#7]
canvas on ubuntu 20.04 on AWS:
  
TASK [role_postgresql : Change postgresql password] ****************************
fatal: [3.90.45.92]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1649662447.09-4259-80806510921286/': Operation not permitted\nchown: changing ownership of '/var/tmp/ansible-tmp-1649662447.09-4259-80806510921286/AnsiballZ_postgresql_user.py': Operation not permitted\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
  

![image](https://user-images.githubusercontent.com/54173243/162688769-fe8eb1c8-80ba-4d0d-bf14-e220efb515eb.png)

**Comment by qiaofeng1227** [comment]
需要等服务启动后 修改用户密码

**Comment by chendelin1982** [comment]
use docker replace it
